title: Poonam Parhar
description: "A blog about troubleshooting the HotSpot JVM"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Poonam Parhar
author-img: poonam.jpg # add your photo
about-author: I am a JVM Sustaining Engineer at Oracle. This is the blogging space to share my troubleshooting experiences with the Hotspot JVM. Views expressed here are solely my own.
social-twitter: poonam_bajaj # add your Twitter handle
social-github: poonamparhar  # add your Github handle
social-linkedin: poonamparhar # add your Linkedin handle
social-email: poonambparhar@gmail.com # add your Email address

# Disqus
discus-identifier: #poonam_parhar

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
